/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TimeSlotsRouteImport } from './routes/time-slots'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as MajorsRouteImport } from './routes/majors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LecturersRouteImport } from './routes/lecturers'
import { Route as FacultiesRouteImport } from './routes/faculties'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CourseClassesRouteImport } from './routes/course-classes'
import { Route as ClassroomsRouteImport } from './routes/classrooms'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as AcademicYearsRouteImport } from './routes/academic-years'
import { Route as AcademicCalendarRouteImport } from './routes/academic-calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacultiesCreateRouteImport } from './routes/faculties.create'
import { Route as FacultiesFacultyIdEditRouteImport } from './routes/faculties.$facultyId.edit'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeSlotsRoute = TimeSlotsRouteImport.update({
  id: '/time-slots',
  path: '/time-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const MajorsRoute = MajorsRouteImport.update({
  id: '/majors',
  path: '/majors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturersRoute = LecturersRouteImport.update({
  id: '/lecturers',
  path: '/lecturers',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultiesRoute = FacultiesRouteImport.update({
  id: '/faculties',
  path: '/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseClassesRoute = CourseClassesRouteImport.update({
  id: '/course-classes',
  path: '/course-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomsRoute = ClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicYearsRoute = AcademicYearsRouteImport.update({
  id: '/academic-years',
  path: '/academic-years',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicCalendarRoute = AcademicCalendarRouteImport.update({
  id: '/academic-calendar',
  path: '/academic-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultiesCreateRoute = FacultiesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => FacultiesRoute,
} as any)
const FacultiesFacultyIdEditRoute = FacultiesFacultyIdEditRouteImport.update({
  id: '/$facultyId/edit',
  path: '/$facultyId/edit',
  getParentRoute: () => FacultiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/academic-years': typeof AcademicYearsRoute
  '/buildings': typeof BuildingsRoute
  '/classrooms': typeof ClassroomsRoute
  '/course-classes': typeof CourseClassesRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/faculties': typeof FacultiesRouteWithChildren
  '/lecturers': typeof LecturersRoute
  '/login': typeof LoginRoute
  '/majors': typeof MajorsRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/students': typeof StudentsRoute
  '/time-slots': typeof TimeSlotsRoute
  '/users': typeof UsersRoute
  '/faculties/create': typeof FacultiesCreateRoute
  '/faculties/$facultyId/edit': typeof FacultiesFacultyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/academic-years': typeof AcademicYearsRoute
  '/buildings': typeof BuildingsRoute
  '/classrooms': typeof ClassroomsRoute
  '/course-classes': typeof CourseClassesRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/faculties': typeof FacultiesRouteWithChildren
  '/lecturers': typeof LecturersRoute
  '/login': typeof LoginRoute
  '/majors': typeof MajorsRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/students': typeof StudentsRoute
  '/time-slots': typeof TimeSlotsRoute
  '/users': typeof UsersRoute
  '/faculties/create': typeof FacultiesCreateRoute
  '/faculties/$facultyId/edit': typeof FacultiesFacultyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/academic-years': typeof AcademicYearsRoute
  '/buildings': typeof BuildingsRoute
  '/classrooms': typeof ClassroomsRoute
  '/course-classes': typeof CourseClassesRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/faculties': typeof FacultiesRouteWithChildren
  '/lecturers': typeof LecturersRoute
  '/login': typeof LoginRoute
  '/majors': typeof MajorsRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/roles': typeof RolesRoute
  '/students': typeof StudentsRoute
  '/time-slots': typeof TimeSlotsRoute
  '/users': typeof UsersRoute
  '/faculties/create': typeof FacultiesCreateRoute
  '/faculties/$facultyId/edit': typeof FacultiesFacultyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-calendar'
    | '/academic-years'
    | '/buildings'
    | '/classrooms'
    | '/course-classes'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/faculties'
    | '/lecturers'
    | '/login'
    | '/majors'
    | '/programs'
    | '/register'
    | '/roles'
    | '/students'
    | '/time-slots'
    | '/users'
    | '/faculties/create'
    | '/faculties/$facultyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-calendar'
    | '/academic-years'
    | '/buildings'
    | '/classrooms'
    | '/course-classes'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/faculties'
    | '/lecturers'
    | '/login'
    | '/majors'
    | '/programs'
    | '/register'
    | '/roles'
    | '/students'
    | '/time-slots'
    | '/users'
    | '/faculties/create'
    | '/faculties/$facultyId/edit'
  id:
    | '__root__'
    | '/'
    | '/academic-calendar'
    | '/academic-years'
    | '/buildings'
    | '/classrooms'
    | '/course-classes'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/faculties'
    | '/lecturers'
    | '/login'
    | '/majors'
    | '/programs'
    | '/register'
    | '/roles'
    | '/students'
    | '/time-slots'
    | '/users'
    | '/faculties/create'
    | '/faculties/$facultyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicCalendarRoute: typeof AcademicCalendarRoute
  AcademicYearsRoute: typeof AcademicYearsRoute
  BuildingsRoute: typeof BuildingsRoute
  ClassroomsRoute: typeof ClassroomsRoute
  CourseClassesRoute: typeof CourseClassesRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRoute
  FacultiesRoute: typeof FacultiesRouteWithChildren
  LecturersRoute: typeof LecturersRoute
  LoginRoute: typeof LoginRoute
  MajorsRoute: typeof MajorsRoute
  ProgramsRoute: typeof ProgramsRoute
  RegisterRoute: typeof RegisterRoute
  RolesRoute: typeof RolesRoute
  StudentsRoute: typeof StudentsRoute
  TimeSlotsRoute: typeof TimeSlotsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-slots': {
      id: '/time-slots'
      path: '/time-slots'
      fullPath: '/time-slots'
      preLoaderRoute: typeof TimeSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/majors': {
      id: '/majors'
      path: '/majors'
      fullPath: '/majors'
      preLoaderRoute: typeof MajorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturers': {
      id: '/lecturers'
      path: '/lecturers'
      fullPath: '/lecturers'
      preLoaderRoute: typeof LecturersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculties': {
      id: '/faculties'
      path: '/faculties'
      fullPath: '/faculties'
      preLoaderRoute: typeof FacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-classes': {
      id: '/course-classes'
      path: '/course-classes'
      fullPath: '/course-classes'
      preLoaderRoute: typeof CourseClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classrooms': {
      id: '/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof ClassroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-years': {
      id: '/academic-years'
      path: '/academic-years'
      fullPath: '/academic-years'
      preLoaderRoute: typeof AcademicYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-calendar': {
      id: '/academic-calendar'
      path: '/academic-calendar'
      fullPath: '/academic-calendar'
      preLoaderRoute: typeof AcademicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculties/create': {
      id: '/faculties/create'
      path: '/create'
      fullPath: '/faculties/create'
      preLoaderRoute: typeof FacultiesCreateRouteImport
      parentRoute: typeof FacultiesRoute
    }
    '/faculties/$facultyId/edit': {
      id: '/faculties/$facultyId/edit'
      path: '/$facultyId/edit'
      fullPath: '/faculties/$facultyId/edit'
      preLoaderRoute: typeof FacultiesFacultyIdEditRouteImport
      parentRoute: typeof FacultiesRoute
    }
  }
}

interface FacultiesRouteChildren {
  FacultiesCreateRoute: typeof FacultiesCreateRoute
  FacultiesFacultyIdEditRoute: typeof FacultiesFacultyIdEditRoute
}

const FacultiesRouteChildren: FacultiesRouteChildren = {
  FacultiesCreateRoute: FacultiesCreateRoute,
  FacultiesFacultyIdEditRoute: FacultiesFacultyIdEditRoute,
}

const FacultiesRouteWithChildren = FacultiesRoute._addFileChildren(
  FacultiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicCalendarRoute: AcademicCalendarRoute,
  AcademicYearsRoute: AcademicYearsRoute,
  BuildingsRoute: BuildingsRoute,
  ClassroomsRoute: ClassroomsRoute,
  CourseClassesRoute: CourseClassesRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRoute,
  FacultiesRoute: FacultiesRouteWithChildren,
  LecturersRoute: LecturersRoute,
  LoginRoute: LoginRoute,
  MajorsRoute: MajorsRoute,
  ProgramsRoute: ProgramsRoute,
  RegisterRoute: RegisterRoute,
  RolesRoute: RolesRoute,
  StudentsRoute: StudentsRoute,
  TimeSlotsRoute: TimeSlotsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
